### ISSUE TITLE
Add videos for RISE and LIME to the tutorials README; update the main README and the ROADMAP

### ISSUE THREAD

**Issue by elboyran** [dianna-ai/dianna#529]
- [x] Add links to the videos mentioned a the XAI literature review issue #489 to the [methods tutorials README](https://github.com/dianna-ai/dianna/tree/main/tutorials)

- [x] Update the main [README Tutorial's section](https://github.com/dianna-ai/dianna#tutorials) swap Embedding and Time series lines, add sentence that videos for explainers have been added.

- [x] Update (accordingly) the [ROADMAP](https://dianna.readthedocs.io/en/latest/ROADMAP.html)
