### ISSUE TITLE
Overview tutorial (create or polish)

### ISSUE THREAD

**Issue by cwmeijer** [dianna-ai/dianna#732]
- [x] Rename the demo notebook to Overview
- [x] Edit the Getting started section from the main README. Point to the overview notebook in the main README.
- [x] Split the notebook into 2 sections: explainers and data modalities

Move the [Getting Started examples from the main README](https://github.com/dianna-ai/dianna?tab=readme-ov-file#getting-started) to the [overview notebook](https://github.com/dianna-ai/dianna/blob/main/tutorials/overview.ipynb)

- [x] Text example
- [x] Image example
- [x] TS example
- [x] Tabular example

++++++++++++++++++++++++++

- [x] Fix the Colab paths in overview tutorial (see the work in #772).

- [x] Correct the nblik file in the docs folder

-------------------------------------

- [x] fix LIME and RISE text tutorial colormaps (and possibly extend with examples), issue #755 
- [x] fix LIME for coffee and weather and RISE for images and weather datasets colormap, issue #770 
- [x] fix download path in the FRB tutorial, see #171.

Below are the original ideas for this issue:

> Maybe the demo notebook is a good starting point.
> Make it a nice generic tutorial.
> Make sure it is linked to from the right places in our readme and tutorial readme.
> Consider removing/shortening the Getting Started README section and moving the content to the demo notebook. See also #721.

**Comment by elboyran** [comment]
Issue #755 addressed by commits https://github.com/dianna-ai/dianna/pull/776/commits/643b478ff8a5466982c3ff9826fb3e1ecff2d0df and https://github.com/dianna-ai/dianna/pull/776/commits/c461e7ca316008bda958ee13fa7f26ffd978d799.

**Comment by elboyran** [comment]
New structure of the overview notebook, Colab and root directory settings; text and image examples are addressed by https://github.com/dianna-ai/dianna/pull/776/commits/eb1b5df725395af42d7d7982af307679daa7e5a1.

**Comment by elboyran** [comment]
Time-series example (RISE on simple extreme temp days) added by https://github.com/dianna-ai/dianna/pull/776/commits/8bd8c52074967b5096d862eb1327578a1f245598.

**Comment by elboyran** [comment]
Tabular regression example added by https://github.com/dianna-ai/dianna/pull/776/commits/fdd72296734333e050c1791f1f9c5e279223a808.

**Comment by elboyran** [comment]
The d[ocumentation](https://dianna.readthedocs.io/en/overview_and_tutorials_change/) looks also nice now ;-)
