### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by elboyran** [dianna-ai/dianna#94]
- [ ] Address relevant JOSS paper requirements described in #102   

- [ ] #135

- [ ] #134

- [x] Create table of methods vs data modalities 

- [ ] #142

- [ ] Consider possibilities found out in issue #100.

- [ ] Suggestions by Faruk & GT in issue #116 

- [ ] Add DIANNA logo

- [ ] #143

**Comment by elboyran** [comment]
Blocked by issue #100 and #

**Comment by egpbos** [comment]
I converted all items here into separate issues.
